### ISSUE TITLE
Add url to readme.md

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/glitch-2.0#15]
Add project demo url to readme

**Comment by TheOrangePuff** [comment]
Just did it but it looks like it's already there, should this be closed?

**Comment by abhijithvijayan** [comment]
Sorry about that.

**Comment by abhijithvijayan** [comment]
@TheOrangePuff you could take a look at https://github.com/ceadoor/cea.ac.in/issues/268
